server:
  port: 8288
  address: 0.0.0.0
  servlet:
    context-path: /
spring:
  jpa:
    properties:
      hibernate:
        default_read_only: true # 查询后修改数据不会提交
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: mysql
  datasource:
  　type: com.alibaba.druid.pool.DruidDataSource
  　filters: stat,wall,log4j
  　dbcp2:
    　min-idle: 5
    　initial-size: 5
    　max-total:
    　max-wait-millis: 20000
  aop:
    proxy-target-class: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
security:
  basic:
    enable: true # 避免跳到security的登录界面
logging:
  config: classpath:log4j2.yml
  level:
    com:
      th: debug
vlife: # 前端代码同步地址
  packroot: http://localhost:8288/oa
  packages: cn.wwwlike,cn.vlife # 平台启用模型所在的多个路径逗号分隔
  generatorPackRoot: cn.vlife # 代码生成的包路径(该路径必须被AdminApplication启动类注解里配置)
file: # 上传图片存储路径
  image:
    path: img
