server:
  port: 8288
  servlet:
    context-path: /oa
spring:
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/auth?useSSL=true&serverTimezone=GMT%2B8&characterEncoding=UTF8
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update #更新或创建表
    show-sql: true
    database: mysql

endpoints:
  metrics:
    sensitive: false

vlife:
  packroot: cn.wwwlike.oa
  email: #注册码发送
    from: vlifelowcode@163.com
    pwd:
  gitee: #gitee登录
    client_id:
    client_secret:
    redirect_uri: http://XXXX:port/login?from=gitee


file:
  image:
    path: d:\\img
    url: http://vlife.cc/img/aaa


