spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=vlife1
    username: sa
    password: ganlanshu626
  jpa:
    hibernate:
      ddl-auto: none #更新或创建表
    show-sql: true
    database: SQL_SERVER
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
endpoints:
  metrics:
    sensitive: false
vlife:
  email: #注册码发送
    from: 222@163.com
    pwd: 3232132
  gitee: #gitee登录
    client_id: 32131
    client_secret: 33333332
    redirect_uri: http://admin.vlife.cc/login?from=gitee
